apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: multiproc-pipeline-cbs # executable id, must be unique across all your workflows (YAML files), please modify this to any value (e.g. code-pipeline-12345) if you are not the only user of your SAP AI Core instance.
  annotations:
    scenarios.ai.sap.com/description: "Test to check CPU parallelization in SAP AI Core"
    scenarios.ai.sap.com/name: "Parallel"
    executables.ai.sap.com/description: "Run an example of the multiprocessing app"
    executables.ai.sap.com/name: "multiprocessing"
  labels:
    scenarios.ai.sap.com/id: "parallel-code"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: amagnani # your docker registry secret
  entrypoint: mypipeline
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblock1

  - name: mycodeblock1
    container:
      image: docker.io/amagnani/parallel-test:01 # Your docker image name
      command: ["/bin/sh", "-c"]
      args:
        - "python /app/src/parallel.py"
